create table BID (SOURCE_ID VARCHAR(64) NOT NULL, SOURCE CHAR(32) NOT NULL, BID NUMERIC(10,4), CREATED_AT DATETIME DEFAULT CURRENT_DATE NOT NULL, UPDATED_AT DATETIME NOT NULL);
create table location(id bigint generated by default as identity (start with 1 increment by 1) not null, latitude float, longitude float, primary key (id));
